### ISSUE TITLE
Remove rule jsx-a11y/media-has-caption

### ISSUE THREAD

**Issue by jesperjohansson** [strt/javascript#1]
![image](https://user-images.githubusercontent.com/21033162/49853818-a8bd0500-fde8-11e8-9e93-afc3b4308f47.png)

Thoughts?

**Comment by alexandernanberg** [comment]
I think it's a valid rule, I'd never think of adding a `caption` element if it weren't for that warning. In the cases where no caption is available you can just disable that eslint rule for that line eg `eslint-disable-next-line jsx-a11y/media-has-caption`

**Comment by Matotomax** [comment]
If it's an accessibility requirement, then I vote to keep it.

**Comment by jesperjohansson** [comment]
Ok, I'll just ignore the rule then
